### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by Ladicle**
convert llmariner/docs using pandoc

### CODE REVIEW

**Review by kkaneda — APPROVED** [review]
Thanks!

**Comment by kkaneda** [comment]
Looks like subsections are sorted in the alphabetical order
image

**Comment by kkaneda** [comment]
hmm, not sure where the configuration exists. @Ladicle , could you please take a look?

**Comment by aya-cloudnatix** [comment]
The order can change by the weight of the page metadata. Some pages have already set the weight in the top of the file, surrounded ---------.

**Comment by kenji-cloudnatix** [comment]
Ah I see!

**Pull request merged**
