### PR TITLE
docs: update architecture diagram

### PR DESCRIPTION
**Pull request by Ladicle**

### CODE REVIEW

**Comment by kkaneda** [comment]
Maybe this is just be, but I still old the file for some reason.
image

https://llmariner.ai/images/architecture_diagram.png shows the new one.

**Comment by kkaneda** [comment]
The architecture diagram looks great. Thanks for doing that!

**Comment by Ladicle** [comment]
I guess Chrome is caching the old version, as my browser displays the most recent one.

**Comment by kkaneda** [comment]
Thanks for checking. I see. Maybe it's because of caching in CDN. I'll check later.

**Pull request merged**
