### PR TITLE
docs: add 'meta-llama/Meta-Llama-3.3-70B-Instruct'

### PR DESCRIPTION
**Pull request by kkaneda**

### CODE REVIEW

**Review by Ladicle — APPROVED** [review]

**Comment by kkaneda** [comment]
This might be because of the AWQ model that I picked up from HuggingFace, but not working.

```
➜ llma chat completions create --model meta-llama-Meta-Llama-3.3-70B-Instruct-awq --role user --completion "You're a software engineer. Please explain what is k8s?"

I see you've sent an empty message! My name is Maya, and I'm a large language model, so I can understand and respond to natural language inputs. Would you like to start a conversation or ask me a question? I can help with everything from answering trivia questions to explaining complex concepts in simple terms.

 I can also help you learn a new skill or hobby. Here are some examples:

 - Would you like to learn a new language?
 - Are you interested in photography and want to know the basics of taking good photos?
 - Maybe you're interested in science and want to know more about climate change?

 Just let me know what's on your mind, and we can start chatting!
```

**Comment by kenji-cloudnatix** [comment]
I'll check the template.

**Comment by kkaneda** [comment]
The issue was that the control plane was an old version that is not compatible with the latest version of engine. 

Updating the control plane fixed the issue.

```
➜ llma chat completions create --model meta-llama-Meta-Llama-3.3-70B-Instruct-awq  --role user --completion "What is k8s?"

**Kubernetes (k8s) Overview**
=====================================

Kubernetes, also known as k8s, is an open-source container orchestration platform for automating the deployment, scaling, and management of containerized applications.

**Key Features**
---------------

* **Container Orchestration**: Deploy and manage containerized applications
* **Scalability**: Scale applications horizontally to handle changes in traffic or demand
* **High Availability**: Ensure application uptime and reliability
* **Self-healing**: Automatically detect and recover from node failures

**Key Components**
-----------------

* **Pods**: The smallest deployable unit, comprising one or more containers
* **ReplicaSets**: Ensure a specified number of replicas (identical pods) are running at any given time
* **Deployments**: Manage rollouts of new versions of an application
* **Services**: Provide a network identity and load balancing for accessing applications

**Use Cases**
-------------

* **Web Applications**: Run scalable, containerized web applications
* **Microservices**: Manage and orchestrate microservices architectures
* **Big Data**: Run distributed data processing workloads
* **Machine Learning**: Train and deploy machine learning models at scale

**Benefits**
------------

* **Improved Efficiency**: Automate deployment and scaling of applications
* **Increased Reliability**: Ensure high availability and self-healing of applications
* **Cost Savings**: Optimize resource utilization and reduce infrastructure costs

Kubernetes is widely used in cloud-native and hybrid environments, and is supported by major cloud providers, including Amazon Web Services (AWS), Google Cloud Platform (GCP), Microsoft Azure, and IBM Cloud
```

**Comment by kkaneda** [comment]
➜ llma chat completions create --model meta-llama-Meta-Llama-3.3-70B-Instruct-awq  --role user --completion "Can you please write a Go code that plays Tetris?"

```go
package main

import (
    "fmt"
    "time"
    "math/rand"
    "os"
    "strings"
)

// Constants
const (
    Width, Height = 10, 20
    BlockSize = 3
)

// Structures
type Piece struct {
    X, Y int
    Color string
    Blocks [][]int
}

// Functions
func NewPiece(pieceType int) Piece {
    pieces := [][]int{
        {{0, 0}, {1, 0}, {2, 0}, {3, 0}}, // I
        {{0, 0}, {1, 0}, {0, 1}, {1, 1}}, // O
        {{0, 0}, {1, 0}, {2, 0}, {2, 1}}, // J
        {{0, 1}, {1, 1}, {2, 1}, {2, 0}}, // L
        {{0, 1}, {1, 1}, {1, 0}, {2, 0}}, // S
        {{0, 0}, {1, 0}, {1, 1}, {2, 1}}, // Z
        {{0, 1}, {1, 0}, {1, 1}, {1, 2}}, // T
    }
    return Piece{
        X:      Width / 2,
        Y:      0,
        Color:  "Yellow",
        Blocks: pieces[pieceType],
    }
}

func PrintGame(board [Height][Width]int, piece Piece) {
    for y := 0; y < Height; y++ {
        for x := 0; x < Width; x++ {
            if y < piece.Y || y > piece.Y+BlockSize {
                if board[y][x] == 1 {
                    fmt.Print("# ")
                } else {
                    fmt.Print(". ")
                }
            } else {
                for _, block := range piece.Blocks {
                    if block[0]+piece.X == x && block[1]+piece.Y == y {
                        fmt.Print("* ")
                        break
                    }
                }
                if piece.Y <= y && y < piece.Y+BlockSize {
                    if board[y][x] == 1 {
                        fmt.Print("# ")
                    } else {
                        fmt.Print(". ")
                    }
                }
            }
        }
        fmt.Println()
    }
    fmt.Println("Score: 0")
    fmt.Println("Lines: 0")
    fmt.Println("Level: 1")
}

func update(board [Height][Width]int, piece *Piece, dx int, dy int) bool {
    // Check if the piece can be moved to the new position
    for _, block := range piece.Blocks {
        newX, newY := piece.X+block[0]+dx, piece.Y+block[1]+dy
        if newX < 0 || newX >= Width || newY < 0 || newY >= Height || board[newY][newX] == 1 {
            return false
        }
    }

    piece.X += dx
    piece.Y += dy
    return true
}

func isRowFull(board [Height][Width]int, row int) bool {
    for _, cell := range board[row] {
        if cell == 0 {
            return false
        }
    }
    return true
}

func removeRow(board [Height][Width]int, row int) [Height][Width]int {
    for i := row; i > 0; i-- {
        for j := 0; j < Width; j++ {
            board[i][j] = board[i-1][j]
        }
    }
    for j := 0; j < Width; j++ {
        board[0][j] = 0
    }
    return board
}

func main() {
    var board [Height][Width]int
    piece := NewPiece(0)
    currScore := 0
    level := 1
    lines := 0
    start := time.Now()

    for {
        PrintGame(board, piece)
        fmt.Print("Enter a command (left, right, down, quit): ")
        var command string
        fmt.Scanln(&command)

        switch strings.ToLower(command) {
        case "left":
            update(board, &piece, -1, 0)
        case "right":
            update(board, &piece, 1, 0)
        case "down":
            if !update(board, &piece, 0, 1) {
                for _, block := range piece.Blocks {
                    board[piece.Y+block[1]][piece.X+block[0]] = 1
                }
                piece = NewPiece(rand.Intn(7))
                // Remove full rows
                for i := Height - 1; i >= 0; i-- {
                    if isRowFull(board, i) {
                        lines++
                        board = removeRow(board, i)
                    }
                }
                // Update score and level
                currScore += 100 * level
                if lines >= level*10 {
                    level++
                }
            }
        case "quit":
            os.Exit(0)
        default:
            fmt.Println("Invalid command")
        }

        // Move the piece down every second
        time.Sleep(time.Second / 2)
    }
}
```

**Pull request merged**
